### ISSUE TITLE
Unicode in python

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Bengali-Alphabet#14]

**Comment by cx0y** [comment]
@lifeparticle 
You created a good project! I like and appreciate this project! but there is no description! can you please give one!

**Comment by lifeparticle** [comment]
@cx0y Thank you! We want something similar 
https://github.com/lifeparticle/Bengali-Alphabet/blob/master/unicode/unicode.rb
in Python

**Comment by cx0y** [comment]
Well! Thank you!

**Comment by lifeparticle** [comment]
Thank you for the pr! @cx0y

**Comment by cx0y** [comment]
Welcome! 😁
